version: "3.7"

services:
  agos-map:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/share/nginx/html:z
    ports:
      - 7001:80
    networks:
      - tg_agos_agos_server_network

networks:
  tg_agos_agos_server_network:
    external: true
